# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='1', upload_to='profile/'),
        ),
    ]
